In [ ]:
!pip install cartoframes

Collecting cartoframes
  Downloading https://files.pythonhosted.org/packages/93/ff/28064bd6e2a5fb4cde7d788cda5cf62cb32799f1427d65c8662d8c57853b/cartoframes-1.2.2-py2.py3-none-any.whl (244kB)
     |████████████████████████████████| 245kB 6.6MB/s
Requirement already satisfied: appdirs<2.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from cartoframes) (1.4.4)
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.7/dist-packages (from cartoframes) (1.1.5)
Collecting geopandas<1.0,>=0.6.0
  Downloading https://files.pythonhosted.org/packages/d7/bf/e9cefb69d39155d122b6ddca53893b61535fa6ffdad70bf5ef708977f53f/geopandas-0.9.0-py2.py3-none-any.whl (994kB)
     |████████████████████████████████| 1.0MB 10.0MB/s
Collecting unidecode<2.0,>=1.1.0
  Downloading https://files.pythonhosted.org/packages/9e/25/723487ca2a52ebcee88a34d7d1f5a4b80b793f179ee0f62d5371938dfa01/Unidecode-1.2.0-py2.py3-none-any.whl (241kB)
     |████████████████████████████████| 245kB 20.3MB/s
Collecting carto<2.0,>=1.11.2
  Downloading https://files.pythonhosted.org/packages/25/e1/d32f14e5827b818aec6509b03fc04867728440035a54878d08c108890a1e/carto-1.11.2-py3-none-any.whl
Collecting semantic-version<3,>=2.8.0
  Downloading https://files.pythonhosted.org/packages/a5/15/00ef3b7888a10363b7c402350eda3acf395ff05bebae312d1296e528516a/semantic_version-2.8.5-py2.py3-none-any.whl
Requirement already satisfied: jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from cartoframes) (2.11.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->cartoframes) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->cartoframes) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->cartoframes) (2018.9)
Collecting fiona>=1.8
  Downloading https://files.pythonhosted.org/packages/9c/fc/9807326c37a6bfb2393ae3e1cca147aa74844562c4d5daa782d6e97ad2bc/Fiona-1.8.20-cp37-cp37m-manylinux1_x86_64.whl (15.4MB)
     |████████████████████████████████| 15.4MB 188kB/s
Collecting pyproj>=2.2.0
  Downloading https://files.pythonhosted.org/packages/11/1d/1c54c672c2faf08d28fe78e15d664c048f786225bef95ad87b6c435cf69e/pyproj-3.1.0-cp37-cp37m-manylinux2010_x86_64.whl (6.6MB)
     |████████████████████████████████| 6.6MB 24.8MB/s
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas<1.0,>=0.6.0->cartoframes) (1.7.1)
Collecting pyrestcli==0.6.11
  Downloading https://files.pythonhosted.org/packages/af/24/d3e7638e30f36396caa4ddc1e25d3f1b5ff76d91738166996e74a9cb4fc0/pyrestcli-0.6.11.tar.gz
Requirement already satisfied: requests>=2.7.0 in /usr/local/lib/python3.7/dist-packages (from carto<2.0,>=1.11.2->cartoframes) (2.23.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2<3.0,>=2.10.1->cartoframes) (2.0.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.0->cartoframes) (1.15.0)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas<1.0,>=0.6.0->cartoframes) (21.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas<1.0,>=0.6.0->cartoframes) (57.0.0)
Collecting cligj>=0.5
  Downloading https://files.pythonhosted.org/packages/73/86/43fa9f15c5b9fb6e82620428827cd3c284aa933431405d1bcf5231ae3d3e/cligj-0.7.2-py3-none-any.whl
Collecting munch
  Downloading https://files.pythonhosted.org/packages/cc/ab/85d8da5c9a45e072301beb37ad7f833cd344e04c817d97e0cc75681d248f/munch-2.5.0-py2.py3-none-any.whl
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas<1.0,>=0.6.0->cartoframes) (2021.5.30)
Collecting click-plugins>=1.0
  Downloading https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas<1.0,>=0.6.0->cartoframes) (7.1.2)
Requirement already satisfied: future>=0.15.2 in /usr/local/lib/python3.7/dist-packages (from pyrestcli==0.6.11->carto<2.0,>=1.11.2->cartoframes) (0.16.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->carto<2.0,>=1.11.2->cartoframes) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->carto<2.0,>=1.11.2->cartoframes) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->carto<2.0,>=1.11.2->cartoframes) (2.10)
Building wheels for collected packages: pyrestcli
  Building wheel for pyrestcli (setup.py) ... done
  Created wheel for pyrestcli: filename=pyrestcli-0.6.11-cp37-none-any.whl size=8499 sha256=8a11edd3a9334558d70b08d0503a1137de7c6628ea33d6eab59f3141c7ee694e
  Stored in directory: /root/.cache/pip/wheels/2f/bb/11/396a62e2d1e718f2bfb02b66726240fbc8d98640bfc0cf1688
Successfully built pyrestcli
Installing collected packages: cligj, munch, click-plugins, fiona, pyproj, geopandas, unidecode, pyrestcli, carto, semantic-version, cartoframes
Successfully installed carto-1.11.2 cartoframes-1.2.2 click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.20 geopandas-0.9.0 munch-2.5.0 pyproj-3.1.0 pyrestcli-0.6.11 semantic-version-2.8.5 unidecode-1.2.0

In [ ]:
import pandas as pd
from geopandas import GeoDataFrame, points_from_xy
import geopandas as gpd
import time

from cartoframes import read_carto, to_carto
from cartoframes.auth import set_default_credentials, Credentials
from cartoframes.viz import *

from cartoframes.data.services import Isolines

from cartoframes.data.observatory import Catalog, Dataset
from cartoframes.data.observatory import Enrichment

In [ ]:
#@title Your credentials
USER_NAME = '' #@param {type:"string"}
API_KEY = '\\' #@param {type:"string"}


set_default_credentials(
    username=USER_NAME,
    api_key=API_KEY
)

In [ ]:
datasets = Catalog().country('usa').category('demographics').provider('usa_acs').datasets
datasets.to_dataframe()

You can find more entities with the Global country filter. To apply that filter run:
	Catalog().country('glo')

                         slug  ...                                                 id
0    acs_sociodemogr_a0c48b07  ...  carto-do-public-data.usa_acs.demographics_soci...
1    acs_sociodemogr_a03fb95f  ...  carto-do-public-data.usa_acs.demographics_soci...
2    acs_sociodemogr_e7b702b0  ...  carto-do-public-data.usa_acs.demographics_soci...
3    acs_sociodemogr_e1e92d8d  ...  carto-do-public-data.usa_acs.demographics_soci...
4    acs_sociodemogr_2960a7d7  ...  carto-do-public-data.usa_acs.demographics_soci...
..                        ...  ...                                                ...
274  acs_sociodemogr_f5f9ac26  ...  carto-do-public-data.usa_acs.demographics_soci...
275  acs_sociodemogr_3fe3e3ec  ...  carto-do-public-data.usa_acs.demographics_soci...
276  acs_sociodemogr_fd3ffe5e  ...  carto-do-public-data.usa_acs.demographics_soci...
277  acs_sociodemogr_6917107d  ...  carto-do-public-data.usa_acs.demographics_soci...
278  acs_sociodemogr_69f1cc12  ...  carto-do-public-data.usa_acs.demographics_soci...

[279 rows x 19 columns]

In [ ]:
dataset = Dataset.get('acs_sociodemogr_fd3ffe5e')
dataset.to_dict()

{'category_id': 'demographics',
 'category_name': 'Demographics',
 'country_id': 'usa',
 'data_source_id': 'sociodemographics',
 'description': 'The American Community Survey (ACS) is an ongoing survey that provides vital information on a yearly basis about the USA and its people. This dataset contains only a subset of the variables that have been deemed most relevant. More info: https://www.census.gov/programs-surveys/acs/about.html',
 'geography_description': 'Shoreline clipped TIGER/Line boundaries. More info: https://carto.com/blog/tiger-shoreline-clip/',
 'geography_id': 'carto-do-public-data.carto.geography_usa_blockgroup_2015',
 'geography_name': 'Census Block Group - United States of America (2015)',
 'id': 'carto-do-public-data.usa_acs.demographics_sociodemographics_usa_blockgroup_2015_5yrs_20122016',
 'is_public_data': True,
 'lang': 'eng',
 'name': 'Sociodemographics - United States of America (Census Block Group, 2016, 5yrs)',
 'provider_id': 'usa_acs',
 'provider_name': 'American Community Survey',
 'slug': 'acs_sociodemogr_fd3ffe5e',
 'temporal_aggregation': '5yrs',
 'time_coverage': '[2012-01-01, 2017-01-01)',
 'update_frequency': None,
 'version': '20122016'}

In [55]:
variables = Catalog().country('usa').category('demographics').provider('usa_acs').datasets[275].variables
variables

You can find more entities with the Global country filter. To apply that filter run:
	Catalog().country('glo')

[<Variable.get('geoid_f3eabab6')> #'US Census Block Groups Geoids',
 <Variable.get('do_date_6b8a00d7')> #'First day of the year the survey was issued',
 <Variable.get('total_pop_99391f48')> #'Total Population. The total number of all people l...',
 <Variable.get('households_7275c832')> #'Households. A count of the number of households in...',
 <Variable.get('male_pop_8737a0c7')> #'Male Population. The number of people within each ...',
 <Variable.get('female_pop_e6f86adb')> #'Female Population. The number of people within eac...',
 <Variable.get('median_age_4116410b')> #'Median Age. The median age of all people in a give...',
 <Variable.get('male_under_5_cc641183')> #'Male under 5 years. The male population over the a...',
 <Variable.get('male_5_to_9_2d60b136')> #'Male age 5 to 9. The male population between the a...',
 <Variable.get('male_10_to_14_acd4f054')> #'Male age 10 to 14. The male population between the...',
 <Variable.get('male_15_to_17_67e58e49')> #'Male age 15 to 17. The male population between the...',
 <Variable.get('male_18_to_19_e18ac28e')> #'Male age 18 and 19. The male population between th...',
 <Variable.get('male_20_9f20425')> #'Male age 20. The male population with an age of tw...',
 <Variable.get('male_21_7ef534b3')> #'Male age 21. The male population with an age of tw...',
 <Variable.get('male_22_to_24_9ee9b55d')> #'Male age 22 to 24. The male population between the...',
 <Variable.get('male_25_to_29_25fff76e')> #'Male age 25 to 29. The male population between the...',
 <Variable.get('male_30_to_34_dcc795ab')> #'Male age 30 to 34. The male population between the...',
 <Variable.get('male_35_to_39_f04ec6b1')> #'Male age 35 to 39. The male population between the...',
 <Variable.get('male_40_to_44_99430a75')> #'Male age 40 to 44. The male population between the...',
 <Variable.get('male_45_to_49_b5ca596f')> #'Men age 45 to 49. The male population between the ...',
 <Variable.get('male_50_to_54_4cf23baa')> #'Men age 50 to 54. The male population between the ...',
 <Variable.get('male_55_to_59_607b68b0')> #'Men age 55 to 59. The male population between the ...',
 <Variable.get('male_65_to_66_55662101')> #'Male age 65 to 66. The male population between the...',
 <Variable.get('male_67_to_69_52462db9')> #'Male age 67 to 69. The male population between the...',
 <Variable.get('male_70_to_74_3ce15e55')> #'Male age 70 to 74. The male population between the...',
 <Variable.get('male_75_to_79_10680d4f')> #'Male age 75 to 79. The male population between the...',
 <Variable.get('male_80_to_84_62595036')> #'Male age 80 to 84. The male population between the...',
 <Variable.get('male_85_and_ove_acf04469')> #'Male age 85 and over. The male population of the a...',
 <Variable.get('female_under_5_3c44707d')> #'Female under 5 years. The female population over t...',
 <Variable.get('female_5_to_9_2920ba6')> #'Female age 5 to 9. The female population between t...',
 <Variable.get('female_10_to_14_f6210f2e')> #'Female age 10 to 14. The female population between...',
 <Variable.get('female_15_to_17_3d107133')> #'Female age 15 to 17. The female population between...',
 <Variable.get('female_18_to_19_bb7f3df4')> #'Female age 18 and 19. The female population betwee...',
 <Variable.get('female_20_adc7cbfb')> #'Female age 20. The female population with an age o...',
 <Variable.get('female_21_dac0fb6d')> #'Female age 21. The female population with an age o...',
 <Variable.get('female_22_to_24_c41c4a27')> #'Female age 22 to 24. The female population between...',
 <Variable.get('female_25_to_29_7f0a0814')> #'Female age 25 to 29. The female population between...',
 <Variable.get('female_30_to_34_86326ad1')> #'Female age 30 to 34. The female population between...',
 <Variable.get('female_35_to_39_aabb39cb')> #'Female age 35 to 39. The female population between...',
 <Variable.get('female_40_to_44_c3b6f50f')> #'Female age 40 to 44. The female population between...',
 <Variable.get('female_45_to_49_ef3fa615')> #'Female age 45 to 49. The female population between...',
 <Variable.get('female_50_to_54_1607c4d0')> #'Female age 50 to 54. The female population between...',
 <Variable.get('female_55_to_59_3a8e97ca')> #'Female age 55 to 59. The female population between...',
 <Variable.get('female_60_to_61_c3cf647f')> #'Female age 60 and 61. The female population betwee...',
 <Variable.get('female_62_to_64_243a81d9')> #'Female age 62 to 64. The female population between...',
 <Variable.get('female_65_to_66_f93de7b')> #'Female age 65 to 66. The female population between...',
 <Variable.get('female_67_to_69_8b3d2c3')> #'Female age 67 to 69. The female population between...',
 <Variable.get('female_70_to_74_6614a12f')> #'Female age 70 to 74. The female population between...',
 <Variable.get('female_75_to_79_4a9df235')> #'Female age 75 to 79. The female population between...',
 <Variable.get('female_80_to_84_38acaf4c')> #'Female age 80 to 84. The female population between...',
 <Variable.get('female_85_and_o_ab655254')> #'Female age 85 and over. The female population of t...',
 <Variable.get('white_pop_f27326c3')> #'White Population. The number of people identifying...',
 <Variable.get('population_1_ye_e5fe1077')> #'Population 1 year and over. All people, male and f...',
 <Variable.get('population_3_ye_c5dd84f2')> #'Population 3 Years and Over. The total number of p...',
 <Variable.get('pop_5_years_ove_e53168ba')> #'Population 5 Years and Over. The number of people ...',
 <Variable.get('pop_16_over_567bd8f')> #'Population age 16 and over. The number of people i...',
 <Variable.get('pop_25_years_ov_45e7a2b5')> #'Population 25 Years and Over. The number of people...',
 <Variable.get('pop_25_64_f48b080e')> #'Population age 25 to 64. The number of people in e...',
 <Variable.get('not_us_citizen__47abdc58')> #'Not a U.S. Citizen Population. The number of peopl...',
 <Variable.get('black_pop_262ed22')> #'Black or African American Population. The number o...',
 <Variable.get('asian_pop_28b3927c')> #'Asian Population. The number of people identifying...',
 <Variable.get('hispanic_pop_c1af7019')> #'Hispanic Population. The number of people identify...',
 <Variable.get('amerindian_pop_d033d4df')> #'American Indian and Alaska Native Population. The ...',
 <Variable.get('other_race_pop_647fb594')> #'Other Race population. The number of people identi...',
 <Variable.get('two_or_more_rac_85acf9d6')> #'Two or more races population. The number of people...',
 <Variable.get('hispanic_any_ra_b0290940')> #'Hispanic of any race',
 <Variable.get('not_hispanic_po_2fe3edab')> #'Population not Hispanic. The number of people not ...',
 <Variable.get('asian_male_45_5_b60a42e9')> #'Asian Men age 45 to 54',
 <Variable.get('asian_male_55_6_a047389a')> #'Asian Men age 55 to 64',
 <Variable.get('black_male_45_5_448e76a4')> #'Black Men age 45 to 54',
 <Variable.get('black_male_55_6_52c30cd7')> #'Black Men age 55 to 64',
 <Variable.get('hispanic_male_4_3a6fef13')> #'Hispanic Men age 45 to 54',
 <Variable.get('hispanic_male_5_2c229560')> #'Hispanic Men age 55 to 64',
 <Variable.get('white_male_45_5_41909de5')> #'White Men age 45 to 54',
 <Variable.get('white_male_55_6_57dde796')> #'White Men age 55 to 64',
 <Variable.get('median_income_848a4e47')> #'Median Household Income in the past 12 Months. Wit...',
 <Variable.get('income_per_capi_4cba726')> #'Per Capita Income in the past 12 Months. Per capit...',
 <Variable.get('income_less_100_c6453b4a')> #'Households with income less than $10,000. The numb...',
 <Variable.get('income_10000_14_94c3c1d4')> #'Households with income of $10,000 to $14,999. The ...',
 <Variable.get('income_15000_19_8080d24d')> #'Households with income of $15,000 to $19,999. The ...',
 <Variable.get('income_20000_24_4a81dd05')> #'Households with income of $20,000 to $24,999. The ...',
 <Variable.get('income_25000_29_5ec2ce9c')> #'Households with income of $25,000 to $29,999. The ...',
 <Variable.get('income_30000_34_b66f2b75')> #'Households with income of $30,000 to $34,999. The ...',
 <Variable.get('income_35000_39_a22c38ec')> #'Households with income of $35,000 to $39,999. The ...',
 <Variable.get('income_40000_44_2d74e2e6')> #'Households with income of $40,000 to $44,999. The ...',
 <Variable.get('income_45000_49_3937f17f')> #'Households with income of $45,000 to $49,999. The ...',
 <Variable.get('income_50000_59_23f0cc4b')> #'Households with income of $50,000 to $59,999. The ...',
 <Variable.get('income_60000_74_32b821f7')> #'Households with income of $60,000 to $74,999. The ...',
 <Variable.get('income_75000_99_584553cf')> #'Households with income of $75,000 to $99,999. The ...',
 <Variable.get('income_100000_1_1e5a8c63')> #'Households with income of $100,000 to $124,999. Th...',
 <Variable.get('income_125000_1_fe1c93c3')> #'Households with income of $125,000 to $149,999. Th...',
 <Variable.get('income_150000_1_34312bf')> #'Households with income of $150,000 to $199,999. Th...',
 <Variable.get('income_200000_o_ea9db70c')> #'Households with income of $200,000 Or More. The nu...',
 <Variable.get('pop_determined__a40f11dc')> #'Population for Whom Poverty Status Determined. The...',
 <Variable.get('poverty_8617d37c')> #'Income In The Past 12 Months Below Poverty Level. ...',
 <Variable.get('gini_index_b2fcd7a7')> #'Gini Index. The Gini index, or index of income con...',
 <Variable.get('housing_units_5012ac37')> #'Housing Units. A count of housing units in each ge...',
 <Variable.get('renter_occupied_769237ea')> #'Renter-Occupied Housing Units Paying Cash Rent Med...',
 <Variable.get('owner_occupied__42374426')> #'Owner-Occupied Housing Units Lower Value Quartile',
 <Variable.get('owner_occupied__a2ce493e')> #'Owner-Occupied Housing Units Median Value. The mid...',
 <Variable.get('owner_occupied__ebbea557')> #'Owner-Occupied Housing Units Upper Value Quartile',
 <Variable.get('occupied_housin_5da1132f')> #'Occupied housing units. A housing unit is classifi...',
 <Variable.get('housing_units_r_d28a6a3c')> #'Renter occupied housing units. All occupied units ...',
 <Variable.get('vacant_housing__80a577af')> #'Vacant Housing Units. The count of vacant housing ...',
 <Variable.get('vacant_housing__69a6549c')> #'Vacant Housing Units for Rent. The count of vacant...',
 <Variable.get('vacant_housing__8e95d955')> #'Vacant Housing Units for Sale. The count of vacant...',
 <Variable.get('dwellings_1_uni_3cdc23e2')> #'Single-family (one unit) detached dwellings. This ...',
 <Variable.get('dwellings_1_uni_b595bafc')> #'Single-family (one unit) attached dwellings. This ...',
 <Variable.get('dwellings_2_uni_75d7993d')> #'Two-family (two unit) dwellings',
 <Variable.get('dwellings_3_to__be1cd18a')> #'Multifamily dwellings with three to 4 units',
 <Variable.get('dwellings_5_to__30f615aa')> #'Apartment buildings with 5 to 9 units',
 <Variable.get('dwellings_10_to_6b8b5ab8')> #'Apartment buildings with 10 to 19 units',
 <Variable.get('dwellings_20_to_5f0a7107')> #'Apartment buildings with 20 to 49 units',
 <Variable.get('dwellings_50_or_92824a13')> #'Apartment buildings with 50 or more units',
 <Variable.get('mobile_homes_c274368e')> #'Mobile homes. A manufactured home is defined as a ...',
 <Variable.get('housing_built_2_26a3cebe')> #'Housing units built in 2005 or later. A house, an ...',
 <Variable.get('housing_built_2_2b47292f')> #'Housing units built between 2000 and 2004. A house...',
 <Variable.get('housing_built_1_918ad031')> #'Housing units built before 1939. A house, an apart...',
 <Variable.get('median_year_str_107238b2')> #'Median Year Structure Built. Median Year Structure...',
 <Variable.get('married_househo_bb4c4a0c')> #'Married households. People in formal marriages, as...',
 <Variable.get('nonfamily_house_c58decdd')> #'Nonfamily Households. A householder living alone o...',
 <Variable.get('family_househol_429aafd6')> #'Family Households. A family consists of a househol...',
 <Variable.get('households_publ_c75616c0')> #'Households on cash public assistance or receiving ...',
 <Variable.get('male_male_house_43c68a85')> #'Households with two male partners. An unmarried pa...',
 <Variable.get('female_female_h_c274cbdb')> #'Households with two female partners. An unmarried ...',
 <Variable.get('children_7eb67ac3')> #'Children under 18 Years of Age. The number of peop...',
 <Variable.get('children_in_sin_961da360')> #'Children under 18 years of age in single female-le...',
 <Variable.get('median_rent_b02560b5')> #'Median Rent. The median contract rent within a geo...',
 <Variable.get('percent_income__d14fc476')> #'Percent of Household Income Spent on Rent. Within ...',
 <Variable.get('rent_burden_not_c93cabb8')> #'Housing units without rent burden computed. Units ...',
 <Variable.get('rent_over_50_pe_44bbdd19')> #'Housing units spending over 50% income on rent. Gr...',
 <Variable.get('rent_40_to_50_p_4e933cfc')> #'Housing units spending 40 to 49.9% income on rent....',
 <Variable.get('rent_35_to_40_p_6f2f113c')> #'Housing units spending 35 to 39.9% income on rent....',
 <Variable.get('rent_30_to_35_p_f4e3f181')> #'Housing units spending 30 to 34.9% income on rent....',
 <Variable.get('rent_25_to_30_p_239b9bd4')> #'Housing units spending 25 to 29.9% income on rent....',
 <Variable.get('rent_20_to_25_p_b5490b2e')> #'Housing units spending 20 to 24.9% income on rent....',
 <Variable.get('rent_15_to_20_p_e5914418')> #'Housing units spending 15 to 19.9% income on rent....',
 <Variable.get('rent_10_to_15_p_77b604df')> #'Housing units spending 10 to 14.9% income on rent....',
 <Variable.get('rent_under_10_p_bb4cebbe')> #'Housing units spending less than 10% on rent. Gros...',
 <Variable.get('owner_occupied__a2e33e5a')> #'Owner-occupied Housing Units',
 <Variable.get('million_dollar__ec43daa1')> #'Owner-occupied Housing Units valued at $1,000,000 ...',
 <Variable.get('mortgaged_housi_35363232')> #'Owner-occupied Housing Units with a Mortgage. The ...',
 <Variable.get('different_house_a147a540')> #'Lived in a different house one year ago in a diffe...',
 <Variable.get('different_house_7ba8f73')> #'Lived in a different house one year ago in the sam...',
 <Variable.get('families_with_y_1ee67ae9')> #'Families with young children (under 6 years of age...',
 <Variable.get('two_parent_fami_da87ec72')> #'Two-parent families with young children (under 6 y...',
 <Variable.get('two_parents_in__1d1f054c')> #'Two-parent families, both parents in labor force w...',
 <Variable.get('two_parents_fat_22ccacb1')> #'Two-parent families, father only in labor force wi...',
 <Variable.get('two_parents_mot_bb95d91b')> #'Two-parent families, mother only in labor force wi...',
 <Variable.get('two_parents_not_b0344794')> #'Two-parent families, neither parent in labor force...',
 <Variable.get('one_parent_fami_aa1d790c')> #'One-parent families with young children (under 6 y...',
 <Variable.get('father_one_pare_14ad9991')> #'One-parent families, father, with young children (...',
 <Variable.get('father_in_labor_d7ef8c4e')> #'One-parent families, father in labor force, with y...',
 <Variable.get('commute_less_10_d5198e05')> #'Number of workers with less than 10 minute commute...',
 <Variable.get('commute_10_14_m_f4275fd1')> #'Number of workers with a commute between 10 and 14...',
 <Variable.get('commute_15_19_m_22e0940')> #'Number of workers with a commute between 15 and 19...',
 <Variable.get('commute_20_24_m_2ef8fe4f')> #'Number of workers with a commute between 20 and 24...',
 <Variable.get('commute_25_29_m_d8f1a8de')> #'Number of workers with a commute between 25 and 29...',
 <Variable.get('commute_30_34_m_674d9ec5')> #'Number of workers with a commute between 30 and 34...',
 <Variable.get('commute_35_44_m_e87de504')> #'Number of workers with a commute between 35 and 44...',
 <Variable.get('commute_60_more_97b2926e')> #'Number of workers with a commute of over 60 minute...',
 <Variable.get('commute_45_59_m_1048e617')> #'Number of workers with a commute between 45 and 59...',
 <Variable.get('commuters_16_ov_cf0e079a')> #'Workers age 16 and over who do not work from home....',
 <Variable.get('walked_to_work_6ce9343e')> #'Walked to Work. The number of workers age 16 years...',
 <Variable.get('worked_at_home_d49230d')> #'Worked at Home. The count within a geographical ar...',
 <Variable.get('no_car_a38cc3c5')> #'Workers age 16 and over with no vehicle. All peopl...',
 <Variable.get('no_cars_f0a375f7')> #'Car-free households. The number of households with...',
 <Variable.get('one_car_d988efb2')> #'One car households. The number of households with ...',
 <Variable.get('two_cars_4cb44242')> #'Two car households. The number of households with ...',
 <Variable.get('three_cars_68da99da')> #'Three car households. The number of households wit...',
 <Variable.get('four_more_cars_7bc55ca8')> #'Four car households. The number of households with...',
 <Variable.get('aggregate_trave_fbe175ad')> #'Aggregate travel time to work. The total number of...',
 <Variable.get('commuters_by_pu_75800dbd')> #'Commuters by Public Transportation. The number of ...',
 <Variable.get('commuters_by_bu_3c60b362')> #'Commuters by Bus. The number of workers age 16 yea...',
 <Variable.get('commuters_by_ca_2b56ff42')> #'Commuters by Car, Truck, or Van. The number of wor...',
 <Variable.get('commuters_by_ca_b064a3ee')> #'Commuters by Carpool. The number of workers age 16...',
 <Variable.get('commuters_by_su_e43a45b0')> #'Commuters by Subway or Elevated. The number of wor...',
 <Variable.get('commuters_drove_90995e0a')> #'Commuters who drove alone. The number of workers a...',
 <Variable.get('group_quarters_a0f5a8a3')> #'Population living in group quarters',
 <Variable.get('associates_degr_68e9d839')> #'Population Completed Associate's Degree. The numbe...',
 <Variable.get('bachelors_degre_4226c90e')> #'Population Completed Bachelor's Degree. The number...',
 <Variable.get('high_school_dip_84eb2931')> #'Population Completed High School. The number of pe...',
 <Variable.get('less_one_year_c_6dd6a71a')> #'Population completed less than one year of college...',
 <Variable.get('masters_degree_dd2f04')> #'Population Completed Master's Degree. The number o...',
 <Variable.get('one_year_more_c_28c1be19')> #'Population completed more than one year of college...',
 <Variable.get('less_than_high__64ccebc6')> #'Less than high school graduate. The number of peop...',
 <Variable.get('high_school_inc_d1d6c6a6')> #'Population with high school degree, including GED....',
 <Variable.get('bachelors_degre_c8161758')> #'Population who completed a bachelor's degree. From...',
 <Variable.get('bachelors_degre_bf813e6c')> #'Population with Bachelors Degree or Higher, Ages 2...',
 <Variable.get('graduate_profes_ce89a869')> #'Population who completed a graduate or professiona...',
 <Variable.get('some_college_an_1467c4e6')> #'Population who completed some college or obtained ...',
 <Variable.get('male_45_64_asso_beb78b72')> #'Men age 45 to 64 who obtained an associate's degre...',
 <Variable.get('male_45_64_bach_cad66aae')> #'Men age 45 to 64 who obtained a bachelor's degree',
 <Variable.get('male_45_64_grad_c2840011')> #'Men age 45 to 64 who obtained a graduate or profes...',
 <Variable.get('male_45_64_less_506da164')> #'Men age 45 to 64 who attained less than a 9th grad...',
 <Variable.get('male_45_64_grad_49a7876b')> #'Men age 45 to 64 who attained between 9th and 12th...',
 <Variable.get('male_45_64_high_2e393735')> #'Men age 45 to 64 who completed high school or obta...',
 <Variable.get('male_45_64_some_d35f7ae7')> #'Men age 45 to 64 who completed some college, no de...',
 <Variable.get('male_45_to_64_f94d4750')> #'Men age 45 to 64 ("middle aged"). The male populat...',
 <Variable.get('employed_pop_3c0ba40a')> #'Employed Population. The number of civilians 16 ye...',
 <Variable.get('unemployed_pop_313163e0')> #'Unemployed Population',
 <Variable.get('pop_in_labor_fo_165b95a0')> #'Population in Labor Force. The number of people in...',
 <Variable.get('not_in_labor_fo_f5e497b6')> #'Population Not in Labor Force. The number of peopl...',

In [47]:

acs_df = dataset.to_dataframe()

In [48]:
acs_df.head()

          geoid     do_date  ...  armed_forces  civilian_labor_force
0  360710119004  2012-01-01  ...           0.0                   0.0
1  340076113001  2012-01-01  ...           0.0                   0.0
2  481130078222  2012-01-01  ...           0.0                   0.0
3  360050144001  2012-01-01  ...           0.0                   0.0
4  530050112006  2012-01-01  ...           0.0                   0.0

[5 rows x 165 columns]

In [ ]:
from google.colab import files

In [39]:
uploads = files.upload()

Saving sample_mastercard_financial_geographicinsights_usa_blockgrou_10.csv to sample_mastercard_financial_geographicinsights_usa_blockgrou_10.csv

In [43]:
import io
df2 = pd.read_csv(io.BytesIO(uploads['sample_mastercard_financial_geographicinsights_usa_blockgrou_10.csv']))
df2.head()

                                            the_geom  ...  avg_spend_amt
0  0106000020E61000000100000001030000000100000006...  ...            0.0
1  0106000020E6100000010000000103000000010000000B...  ...            0.0
2  0106000020E6100000010000000103000000010000000B...  ...            0.0
3  0106000020E6100000010000000103000000010000000B...  ...            0.0
4  0106000020E6100000010000000103000000010000000B...  ...            0.0

[5 rows x 14 columns]

In [56]:
gdf_enrich = Enrichment().enrich_points(df2, variables, geom_col='the_geom')

In [62]:
gdf_enrich.drop(['cartodb_id','segment', 'geo_type', 'txn_cnt', 'acct_cnt', 'avg_ticket', 'avg_freq', 'avg_spend_amt' ], axis=1, inplace = True)

In [68]:
gdf_enrich

                                               the_geom  ...       do_area
0     MULTIPOLYGON (((-73.98579 40.73521, -73.98435 ...  ...  4.194152e+06
1     MULTIPOLYGON (((-73.98071 40.73381, -73.97932 ...  ...  4.194152e+06
2     MULTIPOLYGON (((-73.98071 40.73381, -73.97932 ...  ...  4.194152e+06
3     MULTIPOLYGON (((-73.98071 40.73381, -73.97932 ...  ...  4.194152e+06
4     MULTIPOLYGON (((-73.98071 40.73381, -73.97932 ...  ...  4.194152e+06
...                                                 ...  ...           ...
9224  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN
9225  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN
9226  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN
9227  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN
9228  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN

[9229 rows x 241 columns]

In [69]:
gdf_enrich_retail = gdf_enrich.loc[gdf_enrich['industry'] == 'ret']
gdf_enrich_retail

                                               the_geom  ...       do_area
2     MULTIPOLYGON (((-73.98071 40.73381, -73.97932 ...  ...  4.194152e+06
5     MULTIPOLYGON (((-73.98071 40.73381, -73.97932 ...  ...  4.194152e+06
7     MULTIPOLYGON (((-73.98071 40.73381, -73.97932 ...  ...  4.194152e+06
18    MULTIPOLYGON (((-73.96267 40.73645, -73.96260 ...  ...           NaN
19    MULTIPOLYGON (((-73.96267 40.73645, -73.96260 ...  ...           NaN
...                                                 ...  ...           ...
9217  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN
9218  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN
9219  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN
9220  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN
9224  MULTIPOLYGON (((-73.96083 40.74364, -73.96118 ...  ...           NaN

[2439 rows x 241 columns]

In [70]:
from google.colab import files
gdf_enrich_retail.to_csv('retail_socio.csv') 
files.download('retail_socio.csv')